/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Sat Apr 29 16:08:38 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_hwLCD_server_h_)
#define _hwLCD_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "hwLCD.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for LCDService.
 */
class LCDService_service : public erpc::Service
{
public:
    LCDService_service() : Service(kLCDService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for lcd_locate of LCDService interface. */
    erpc_status_t lcd_locate_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for lcd_cls of LCDService interface. */
    erpc_status_t lcd_cls_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for lcd_rows of LCDService interface. */
    erpc_status_t lcd_rows_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for lcd_columns of LCDService interface. */
    erpc_status_t lcd_columns_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for lcd_putc of LCDService interface. */
    erpc_status_t lcd_putc_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "hwLCD.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return LCDService_service service object. */
erpc_service_t create_LCDService_service(void);

/*! @brief Destroy LCDService_service service object. */
void destroy_LCDService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _hwLCD_server_h_
